# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Docker_Containers',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/Docker_Containers',
                'lib_path': 'Docker_Containers'},
  'syms': {'Docker_Containers.core': {'Docker_Containers.core.foo': ('core.html#foo', 'Docker_Containers/core.py')}}}
