# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/IaaS_docs',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/IaaS_docs',
                'lib_path': 'IaaS_docs'},
  'syms': {}}
